name: Build and deploy
on:
  push:
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'LICENCE'
      - 'CODEOWNERS'
    branches:
      - master

jobs:
  enhetstester:
    name: Enhetstester
    runs-on: ubuntu-latest
    steps:
      - name: Hente kode
        uses: actions/checkout@v2.3.2
      - name: Sette opp Java
        uses: actions/setup-java@v1
        with:
          java-version: '13.x'
      - name: Cache Maven repository
        uses: actions/cache@v2.1.1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: KjÃ¸re tester
        run: ./mvnw clean test --settings ./.m2/settings.xml
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

  docker-and-nais-deploy:
    name: Laste opp docker image og deploye
    needs: enhetstester
    runs-on: ubuntu-latest
    steps:
      - name: Hente kode
        uses: actions/checkout@v2.3.2
      - name: Sette opp Java
        uses: actions/setup-java@v1
        with:
          java-version: '13.x'
      - name: Cache Maven repository
        uses: actions/cache@v2.1.1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Bygge JAR
        run: ./mvnw clean package -DskipTests --settings ./.m2/settings.xml
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      - name: Sette Docker- navn og tag
        env:
          DOCKER_IMAGE: docker.pkg.github.com/${{ github.repository }}/k9-punsj
        run: |
          echo $DOCKER_IMAGE > .docker_image
          echo "$(date "+%Y.%m.%d")-$(git rev-parse --short HEAD)" > .docker_tag
          echo "::set-env name=IMAGE::$(cat .docker_image):$(cat .docker_tag)"
      - name: Bygge Docker image
        run: docker build . --pull -t $(cat .docker_image):$(cat .docker_tag)
      - name: Laste opp Docker image
        run: |
          echo "$GITHUB_ACCESS_TOKEN" | docker login --username "x-access-token" --password-stdin https://docker.pkg.github.com
          docker push $(cat .docker_image):$(cat .docker_tag)
          docker tag $(cat .docker_image):$(cat .docker_tag) $(cat .docker_image):latest
          docker push $(cat .docker_image):latest
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
      - name: Deploye til dev
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: nais/dev-fss.yml
