name: Build and deploy
on:
  push:
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'LICENCE'
      - 'CODEOWNERS'
    branches:
      - master

jobs:
  enhetstester:
    name: Enhetstester
    runs-on: ubuntu-latest
    steps:
      - name: Hente kode
        uses: actions/checkout@v1
      - name: Sette opp Java
        uses: actions/setup-java@v1
        with:
          java-version: '13.x'
      - name: KjÃ¸re tester
        run: ./mvnw clean test

  docker-and-nais-deploy:
    name: Laste opp docker image og deploye
    needs: enhetstester
    runs-on: ubuntu-latest
    steps:
      - name: Hente kode
        uses: actions/checkout@v1
      - name: Sette opp Java
        uses: actions/setup-java@v1
        with:
          java-version: '13.x'
      - name: Bygge JAR
        run: ./mvnw clean package -DskipTests
      - name: Sette Docker- navn og tag
        env:
          DOCKER_IMAGE: docker.pkg.github.com/${{ github.repository }}/k9-punsj
        run: |
          echo $DOCKER_IMAGE > .docker_image
          echo "$(date "+%Y.%m.%d")-$(git rev-parse --short HEAD)" > .docker_tag
      - name: Bygge Docker image
        run: docker build . --pull -t $(cat .docker_image):$(cat .docker_tag)
      - name: Laste opp Docker image
        run: |
          echo "$GITHUB_ACCESS_TOKEN" | docker login --username "x-access-token" --password-stdin https://docker.pkg.github.com
          docker push $(cat .docker_image):$(cat .docker_tag)
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
      - name: Deploye til dev
        uses: navikt/deployment-cli/action@0.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          cluster: prod-fss
          team: k9-saksbehandling
          resources: nais/dev-fss.yml
